const cartTypes = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  REDUCE_CART_ITEM: 'REDUCE_CART_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  SELECT_SIZE: 'SELECT_SIZE',
  SELECT_COLOUR: 'SELECT_COLOUR'
};

export default cartTypes;