const additionalTypes = {
    ADD_SIZE_CHART_START: 'ADD_SIZE_CHART_START',
    FETCH_SIZE_CHART_START: 'FETCH_SIZE_CHART_START',
    SET_SIZE_CHART: 'SET_SIZE_CHART',
    DELETE_SIZE_CHART: 'DELETE_SIZE_CHART',
}